# Base configuration
exclude: [".rvmrc", ".rbenv-version", "README.md", "changelog.md"]
markdown: kramdown
highlighter: pygments
permalink: pretty

collections:
  pages:
    output: true
    permalink: /:path/

# Title
name: DMPED Economic Intelligence Dashboard
subtitle: 'Deputy Mayor for Planning & Economic Development | Muriel Bowser, Mayor'

# Author/Organization info to be displayed in the templates
author:
  name: Office of the Deputy Mayor for Planning and Economic Development
  url: http://dmped.dc.gov

# When using this template with a project (repository) page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
baseurl: '/econintel-cotw'

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: '/assets/img/we-are-wdc.png'
logoalt: We Are Washington DC

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Chart of the Week
  internal: true
  url: ./
- text: May 2016
  internal: true
  url: 05-2016.html
- text: April 2016
  internal: true
  url: 04-2016.html
- text: March 2016
  internal: true
  url: 03-2016.html

# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: econintel-cotw
  description:
  url: https://github.com/DCgov/econintel-cotw

# google_analytics_ua: TBA

# Style Variables
brand_color: "#BF0000"
